=== mitrais-cdc-js/starhackit/server/src/plugins/users/raml/user.out.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "createdAt": {
      "type": "string"
    },
    "updatedAt": {
      "type": "string"
    },
    "profile": {
      "type": "object",
      "properties": {
        "biography": {
          "type": "string"
        }
      },
      "required": [
        "biography"
      ]
    },
    "auth_provider": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "authId": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "authId"
        ]
      }
    }
  },
  "required": [
    "id",
    "username",
    "email",
    "firstName",
    "lastName",
    "createdAt",
    "updatedAt",
    "profile"
  ]
}

=== mitrais-cdc-js/starhackit/server/src/plugins/users/raml/user.out.sample.json
{
  "id": "6fba6aca-db12-4eb1-8ae6-918cf20e0f8c",
  "username": "Laura.Jennie.Reeves",
  "email": "Laura.Jennie.Reeves@mail.com",
  "firstName": "Laura",
  "lastName": "Jennie",
  "createdAt": "2016-05-28T15:00:56.358Z",
  "updatedAt": "2016-05-28T15:00:56.358Z",
  "profile": {
    "biography": "Ciao"
  },
  "auth_provider": [{
    "name": "facebook",
    "authId": "1234567890"
  }]
}
